---
- name: Create main Postgres configuration
  ansible.builtin.template:
    src: postgresql.conf.j2
    dest: "{{ postgres_conf_directory }}/postgresql.conf"
    owner: root
    group: "{{ postgres_group }}"
    mode: "0640"

- name: Create host-based auth config
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: "{{ postgres_conf_directory }}/pg_hba.conf"
    mode: "0640"
    owner: root
    group: "{{ postgres_group }}"
  notify: Reload postgresql

- name: Create identity-mapping file
  ansible.builtin.template:
    src: pg_ident.conf.j2
    dest: "{{ postgres_conf_directory }}/pg_ident.conf"
    mode: "0640"
    owner: root
    group: "{{ postgres_group }}"
  notify: Reload postgresql

- name: Create service file
  ansible.builtin.template:
    src: pg_service.conf.j2
    dest: "/etc/pg_service.conf"
    mode: "0644"
    owner: root
    group: root

- name: Tell psql to use correct socket location
  ansible.builtin.template:
    src: profile.sh.j2
    dest: "{{ item }}"
    owner: root
    group: root
    mode: "0755"
  with_items:
    - /etc/profile.d/postgresql.sh
    - "{{ postgres_home_directory }}/.profile"
    - "{{ postgres_home_directory }}/.bashrc"

- name: Stat Postgres version
  ansible.builtin.stat:
    path: "{{ postgres_data_directory }}/PG_VERSION"
  register: postgres_version

# Using sudo because become_user may be overridden
- name: Initialize database
  ansible.builtin.command: sudo -Hu {{ postgres_user }} {{ postgres_initdb }} --locale {{ postgres_locale }} -E {{ postgres_encoding }} -D {{ postgres_data_directory
    }}
  when: not postgres_version.stat.exists

- name: Include Postgres config
  ansible.builtin.template:
    src: postgresql_include.conf.j2
    dest: "{{ postgres_data_directory }}/postgresql.conf"
    mode: "0640"
    owner: root
    group: "{{ postgres_group }}"

- name: Create unit file
  ansible.builtin.template:
    src: postgresql.service.j2
    dest: /etc/systemd/system/postgresql.service
    mode: "0644"
    owner: root
    group: root
  register: unitfile
  vars:
    pg_ctl_path: "/usr/lib/postgresql/{{ pg_ver.stdout }}/bin/pg_ctl"

- name: Reload systemd
  ansible.builtin.command: systemctl daemon-reload
  when: unitfile.changed

- name: Enable and start
  ansible.builtin.service:
    name: postgresql.service
    state: started
    enabled: true
  when: not unitfile.changed

- name: Enable and restart
  ansible.builtin.service:
    name: postgresql.service
    state: restarted
    enabled: true
  when: unitfile.changed

- name: Ensure users exist
  community.general.postgresql_user: "{{ item }}"
  no_log: true # Because otherwise password might get logged.
  loop: "{{ postgres_users }}"

- name: Ensure databases exist
  community.general.postgresql_db: "{{ item }}"
  loop: "{{ postgres_dbs }}"
