---
- name: Install apt packages
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-client
      - postgresql-doc
      - libpq-dev
      - python3-psycopg2
  register: apt

- name: Stop PostgreSQL
  ansible.builtin.service:
    name: postgresql.service
    state: stopped
  when: apt.changed

- name: Get postgresql version
  ansible.builtin.shell: "dpkg-query --showformat='${Version}' --show postgresql | cut -d'+' -f1"
  changed_when: false
  check_mode: false
  register: pg_ver

- name: Delete default postgres unit
  ansible.builtin.file:
    path: /lib/systemd/system/postgresql@.service
    state: absent
  register: del_unit

- name: Stop default postgres unit
  ansible.builtin.service:
    name: "postgresql@{{ pg_ver.stdout }}{% if ansible_distribution == 'Debian' %}-main{% endif %}.service"
    state: stopped
    enabled: false
  when: del_unit.changed

- name: Reset failed state of default postgres unit
  ansible.builtin.command: "systemctl reset-failed postgresql@{{ pg_ver.stdout }}{% if ansible_distribution == 'Debian' %}-main{% endif %}.service"
  ignore_errors: true
  changed_when: false
  when: del_unit.changed

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: del_unit.changed

- name: Ensure Postgres group exists
  ansible.builtin.group:
    name: "{{ postgres_group }}"
    system: true

- name: Ensure Postgres user exists
  ansible.builtin.user:
    name: "{{ postgres_user }}"
    group: "{{ postgres_group }}"
    shell: /bin/false
    home: "{{ postgres_home_directory }}"
    comment: "PostgreSQL user"
    createhome: false
    system: true

- name: Create configuration directory
  ansible.builtin.file:
    path: "{{ postgres_conf_directory }}"
    state: directory
    mode: "0750"
    owner: root
    group: postgres

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
    owner: "{{ postgres_user }}"
    group: "{{ postgres_group }}"
  with_items:
    - "{{ postgres_data_directory }}"
    - "{{ postgres_log_directory }}"
    - "{{ postgres_home_directory }}"

- name: Set path to postgres utilities
  ansible.builtin.set_fact:
    "{{ item.name }}": "{% if pg_ver.stdout %}/usr/lib/postgresql/{{ pg_ver.stdout }}/bin/{{ item.value }}{% else %}{{ item.default }}{% endif %}"
  with_items:
    - name: postgres_initdb
      value: initdb
      default: postgres_default_initdb
